import jsPDF from "jspdf";

export function generateInvoicePDF(invoice: any, contract: any, company: any) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // ===== HEADER =====
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, 35, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", 15, 22);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("BidWell", pageWidth - 15, 15, { align: "right" });
  doc.text("From Tender to Payment", pageWidth - 15, 22, { align: "right" });
  
  // ===== COMPANY INFO =====
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(company?.name || "Your Company Name", 15, 50);
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  const companyLines = [
    company?.address || "Address not provided",
    company?.gst_number ? `GST: ${company.gst_number}` : "",
    company?.pan_number ? `PAN: ${company.pan_number}` : "",
    company?.contact_email || "",
    company?.contact_phone || "",
  ].filter(Boolean);
  
  companyLines.forEach((line, i) => {
    doc.text(line, 15, 57 + i * 5);
  });
  
  // ===== INVOICE DETAILS =====
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Invoice No:", pageWidth - 80, 50);
  doc.text("Date:", pageWidth - 80, 57);
  doc.text("Status:", pageWidth - 80, 64);
  
  doc.setFont("helvetica", "normal");
  doc.text(invoice.invoice_no || "N/A", pageWidth - 15, 50, { align: "right" });
  doc.text(new Date(invoice.submitted_at).toLocaleDateString("en-IN"), pageWidth - 15, 57, { align: "right" });
  doc.text((invoice.status || "").toUpperCase(), pageWidth - 15, 64, { align: "right" });
  
  // ===== LINE =====
  doc.setDrawColor(220, 220, 220);
  doc.line(15, 90, pageWidth - 15, 90);
  
  // ===== CONTRACT INFO =====
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("CONTRACT:", 15, 100);
  doc.setFont("helvetica", "normal");
  doc.text(contract?.title || "N/A", 15, 107);
  
  // ===== TABLE HEADER =====
  doc.setFillColor(240, 240, 240);
  doc.rect(15, 120, pageWidth - 30, 10, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Description", 20, 127);
  doc.text("Amount", pageWidth - 20, 127, { align: "right" });
  
  // ===== TABLE ROW =====
  doc.setFont("helvetica", "normal");
  doc.text(`Invoice ${invoice.invoice_no}`, 20, 140);
  doc.text(`Rs. ${invoice.amount.toLocaleString("en-IN")}`, pageWidth - 20, 140, { align: "right" });
  
  // ===== LINE =====
  doc.line(15, 150, pageWidth - 15, 150);
  
  // ===== TOTAL =====
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("TOTAL AMOUNT:", pageWidth - 80, 162);
  doc.setTextColor(37, 99, 235);
  doc.text(`Rs. ${invoice.amount.toLocaleString("en-IN")}`, pageWidth - 20, 162, { align: "right" });
  
  // ===== PAYMENT TERMS =====
  doc.setTextColor(80, 80, 80);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Payment Terms:", 15, 185);
  doc.text("Please process this invoice at the earliest.", 15, 191);
  doc.text("For queries, contact the company details mentioned above.", 15, 197);
  
  // ===== FOOTER =====
  doc.setDrawColor(220, 220, 220);
  doc.line(15, 210, pageWidth - 15, 210);
  
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by BidWell - AI Contract Operating System", pageWidth / 2, 218, { align: "center" });
  doc.text("This is a system generated invoice.", pageWidth / 2, 223, { align: "center" });
  
  // ===== SAVE =====
  doc.save(`${invoice.invoice_no || "invoice"}.pdf`);
}
